# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a1d033d940dfd441ee26a288c012c53d547f74995d6029bfc8d063e76407a2aa9e314cca05f3d788a15074664fde7dbf51c53573676255db34bb0171b6e813b

test:
  secret_key_base: bd162b13b77c870d602265543a55eab284f0fef63ba9f8a6e4f008172d743a1b8785fdb270c84dde5a787a6971494c1aad1c2fb15664663609b1acf8e41f93ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
